### ISSUE TITLE
App crashes on SpannableString

### ISSUE THREAD

**Issue by sunilsolanki-alight** [Alex-Dobrynin/Controls.UserDialogs.Maui#22]
We observed crash issue on firebase crashalytics with below trace.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
       at android.text.SpannableString.<init>(SpannableString.java:34)
       at android.text.SpannableString.<init>(SpannableString.java:43)
       at crc641a3c7a9fa982c507.AbstractAppCompatDialogFragment_1.n_onCreateDialog(AbstractAppCompatDialogFragment_1.java)
       at crc641a3c7a9fa982c507.AbstractAppCompatDialogFragment_1.onCreateDialog(AbstractAppCompatDialogFragment_1.java:49)
       at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:930)
       at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:844)
       at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1755)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:527)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7617)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Comment by Alex-Dobrynin** [comment]
Have you read the applying form? please provide the repro project. without it i cannot help you

**Comment by sunilsolanki-alight** [comment]
We are not able to reproduce it in lower environment, but getting fatal logs on firebase for alerts.

**Comment by Alex-Dobrynin** [comment]
And how I supposed to help you?

**Comment by sunilsolanki-alight** [comment]
This issue is only occurred, when the message parameter is null for the Alert/Config dialogs.

**Comment by Alex-Dobrynin** [comment]
updated library to the v1.6.0, added nullability checks
please read the docs FAQ №2
