### ISSUE TITLE
crash on iOS with last maui workload... (System.NullReferenceException)    at Controls.UserDialogs.Maui.HudDialog.BeforeShow(ProgressHUD hud)

### ISSUE THREAD

**Issue by ChrisDox** [Alex-Dobrynin/Controls.UserDialogs.Maui#25]
**Describe the bug**
I update my machine with Sequoia, last xcode, last maui workload (all for IOS 18) and now there is a crash 
The crash is on iOS 18 but also in 17.5 or 17 with various devices on simultor
The error is 
Unhandled managed exception: Object reference not set to an instance of an object. (System.NullReferenceException)
   at Controls.UserDialogs.Maui.HudDialog.BeforeShow(ProgressHUD hud) 
   
   Complete stack 
   Unhandled managed exception: Object reference not set to an instance of an object. (System.NullReferenceException)
   at Controls.UserDialogs.Maui.HudDialog.BeforeShow(ProgressHUD hud)
   at Controls.UserDialogs.Maui.HudDialog.<Show>b__6_1()
   at Foundation.NSActionDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 64
--- End of stack trace from previous location ---
   at Foundation.NSObject.InvokeOnMainThread(Action action) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:line 811
   at Controls.UserDialogs.Maui.HudDialog.Show()
   at Controls.UserDialogs.Maui.HudDialog.Update(HudDialogConfig config)
   at Controls.UserDialogs.Maui.UserDialogsImplementation.CreateHudInstance(HudDialogConfig config)
   at Controls.UserDialogs.Maui.UserDialogsImplementation.CreateOrUpdateHud(HudDialogConfig config)
   at Controls.UserDialogs.Maui.UserDialogsImplementation.Loading(String message, String cancelText, Boolean show, Nullable`1 maskType, Action cancel)
   at Controls.UserDialogs.Maui.UserDialogsImplementation.ShowLoading(String message, Nullable`1 maskType)

**To Reproduce**
just in my homepage viewModel
_userDialogs.ShowLoading("Loading");
and there is the crash

**Desktop (please complete the following information):**
 - OS: Mac OS Sequoia 15.0
 Maui workload 8.0.402.1 from SDK 8.0.400
XCode 16

**Smartphone (please complete the following information):**
 - Device: iphone 16 on simulator
 - OS: iOS 18

**Did you found a workaround?**
No

**Comment by Alex-Dobrynin** [comment]
could you provide test project here, where this bug can be reproduced?

**Comment by ChrisDox** [comment]
the error is on iOS in HudDialog.cs > Show()
ProgressHUD hud = ProgressHUD.For(this._keyWindow);
this.BeforeShow(hud);
          
--> hud is null here so in BeforeShow there is the crash.

The problem is only when i use       _userDialogs.ShowLoading("Loading");  in the viewModel of first Page of app ...

If there is an another page before (for launching app) and after my viewModel with _userDialogs.ShowLoading("Loading"); , this works.

**Comment by Alex-Dobrynin** [comment]
@ChrisDox I asked you to provide repro project here, not the description. Please put here .zip or link to the project which i can open and run and see the crash

**Comment by ChrisDox** [comment]
I create a small project with same problem 
[MauiApp1.zip](https://github.com/user-attachments/files/17236199/MauiApp1.zip)

**Comment by ChrisDox** [comment]
Any progress @Alex-Dobrynin  ?
I made a workaround, this is a bad workaround but now the ShowLoading works
I think ShowLoading wants to display while the page has not yet finished loading...
The problem is only when loading the first page right after the splashscreen 


#if IOS
        await Task.Delay(1000);
#endif
        _userDialogs.ShowLoading("Un instant s'il vous plait, je récupère vos données...");

**Comment by Alex-Dobrynin** [comment]
I'm on my vacation now, after vacation will be fixing this

**Comment by Alex-Dobrynin** [comment]
Ok, I have investigated this issue and unfortunately for you, this is not a bug, since there is no window created at the moment of calling loading dialog, and therefore it cannot create a HUD dialog, and the best way for you to show loading dialog on app start is to show it from `OnAppearing` method of your start page, because it is calling right after the window is created and page is attached to it.

**Comment by asi-evin** [comment]
@Alex-Dobrynin I tried your work-a-round and it did not work. I adjusted the original sample with your work-a-round and have attached it:

[MauiApp1(2).zip](https://github.com/user-attachments/files/17379254/MauiApp1.2.zip)

I will also point out that when the Fault is fired, the main page **_IS_** displayed, so I find it hard to beleive there isn't a window. Do you have any other ideas other than the delay? Here's the crash log in case that helps also.

```
INFO: 2024-10-15 09:55:29.451 MauiApp1[2436:1238494] 
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Controls.UserDialogs.Maui.HudDialog.BeforeShow(ProgressHUD hud)
   at Controls.UserDialogs.Maui.HudDialog.<Show>b__6_1()
   at Foundation.NSActionDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 64
   at Foundation.NSObject.InvokeOnMainThread(Action action) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:line 811
   at Controls.UserDialogs.Maui.HudDialog.Show()
   at Controls.UserDialogs.Maui.HudDialog.Update(HudDialogConfig config)
   at Controls.UserDialogs.Maui.UserDialogsImplementation.CreateHudInstance(HudDialogConfig config)
   at Controls.UserDialogs.Maui.UserDialogsImplementation.CreateOrUpdateHud(HudDialogConfig config)
   at Controls.UserDialogs.Maui.UserDialogsImplementation.Loading(String message, String cancelText, Boolean show, Nullable`1 maskType, Action cancel
INFO: )
   at Controls.UserDialogs.Maui.UserDialogsImplementation.ShowLoading(String message, Nullable`1 maskType)
   at MauiApp1.ViewModels.MainPageViewModel.InitializeAsync() in C:\Users\EBallantyne\Downloads\MauiApp1\MauiApp1\MauiApp1\ViewModels\MainPageViewModel.cs:line 22
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 179
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at MauiApp1.Program.Main(String[] args) in C:\Users\EBal
Thread started: <Thread Pool> #7
INFO: 	0x1053dc458 - /private/var/containers/Bundle/Application/35FBDB13-73A2-499C-998D-2D902A0E35DA/MauiApp1.app/MauiApp1 : xamarin_find_protocol_wrapper_type
	0x105642540 - /private/var/containers/Bundle/Application/35FBDB13-73A2-499C-998D-2D902A0E35DA/MauiApp1.app/MauiApp1 : AppleCryptoNative_X509ImportCollection
	0x1056e24c8 - /private/var/containers/Bundle/Application/35FBDB13-73A2-499C-998D-2D902A0E35DA/MauiApp1.app/MauiApp1 : AppleCryptoNative_X509ImportCollection
	0x1053ef888 - /private/var/containers/Bundle/Application/35FBDB13-73A2-499C-998D-2D902A0E35DA/MauiApp1.app/MauiApp1 : xamarin_get_original_working_directory_path
	0x10574acdc - /private/var/containers/Bundle/Application/35FBDB13-73A2-499C-998D-2D902A0E35DA/MauiApp1.app/MauiApp1 : AppleCryptoNative_X509ImportCollection
	0x1b34bf154 - /usr/lib/dyld : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instru
INFO: ction pointer (0x1d89782ec):0x1d89782dc  ff 0f 5f d6 c0 03 5f d6 10 29 80 
INFO: 03 d5 fd 
Thread started: .NET TP Gate #8
INFO: 7b bf a9 fd 03 00 91  ...T.#...{......
0x1d89782fc  2a ec ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  
INFO: *...
INFO: n cancel)
   at Controls.UserDialogs.Maui.UserDialogsImplementation.ShowLoading(String message, Nullable`1 maskType)
   at MauiApp1.ViewModels.MainPageViewModel.InitializeAsync() in C:\Users\EBallantyne\Downloads\MauiApp1\MauiApp1\MauiApp1\ViewModels\MainPageViewModel.cs:line 22
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 179
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at MauiApp1.Program.Main(String[] args) in C:\Us
INFO: 2024-10-15 09:55:29.520 MauiApp1[2436:1238494] Unhandled managed exception: Object reference not set to an instance of an object. (System.NullReferenceException)
   at Controls.UserDialogs.Maui.HudDialog.BeforeShow(ProgressHUD hud)
   at Controls.UserDialogs.Maui.HudDialog.<Show>b__6_1()
   at Foundation.NSActionDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 64
   at Foundation.NSObject.InvokeOnMainThread(Action action) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:line 811
   at Controls.UserDialogs.Maui.HudDialog.Show()
   at Controls.UserDialogs.Maui.HudDialog.Update(HudDialogConfig config)
   at Controls.UserDialogs.Maui.UserDialogsImplementation.CreateHudInstance(HudDialogConfig config)
   at Controls.UserDialogs.Maui.UserDialogsImplementation.CreateOrUpdateHud(HudDialogConfig config)
   at Controls.UserDialogs.Maui.UserDialogsImplementation.Loading(String message, String cancelText, Boolean show, Nullable`1 maskType, Actio
INFO: ers\EBallantyne\Downloads\MauiApp1\MauiApp1\MauiApp1\Platforms\iOS\Program.cs:line 13

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10570cb64 - /private/var/containers/Bundle/Application/35FBDB13-73A2-499C-998D-2D902A0E35DA/MauiApp1.app/MauiApp1 : AppleCryptoNative_X509ImportCollection
	0x1056f7a50 - /private/var/containers/Bundle/Application/35FBDB13-73A2-499C-998D-2D902A0E35DA/MauiApp1.app/MauiApp1 : AppleCryptoNative_X509ImportCollection
	0x105830ab4 - /private/var/containers/Bundle/Application/35FBDB13-73A2-499C-998D-2D902A
INFO: 0E35DA/MauiApp1.app/MauiApp1 : AppleCryptoNative_X509ImportCollection
	0x10570c354 - /private/var/containers/Bundle/Application/35FBDB13-73A2-499C-998D-2D902A0E35DA/MauiApp1.app/MauiApp1 : AppleCryptoNative_X509ImportCollection
	0x1ec6aee9c - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x1ec76bc0c - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x197c77ba0 - /usr/lib/system/libsystem_c.dylib : abort

INFO: .....{...._.
0x1d897830c  c0 03 5f d6 10 27 80 d2 01 10 00 d4 03 01 00 54  .._..'..
INFO: d2 01 10 00 d4  .._..._..)......
0x1d89782ec  03 01 00 54 7f 23 
INFO: .......T

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================

INFO: Closing debug connection from device (USB)
INFO: Disposing input and output streams...
INFO: Closing debug connection from remote debugger (TCP)
INFO: Disposing input and output streams...
INFO: Disposing console and debugger streams...
ERROR: An error occurred while writing to the debug stream. Details: ObjectDisposed_Generic
ObjectDisposed_ObjectName_Name, UsbStream
The app has been terminated.
```

**Comment by asi-evin** [comment]
@ChrisDox I did find a work-a-round. I found that you can override the "OnActived" lifecycle event and it seems to work. Caveat it you'll need a flag to determine if you've already initialized as the event will fire EVERY time the app comes into the foreground. Code looks like so:

```c#
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()

            ...

            .ConfigureLifecycleEvents(events =>
            {
#if IOS
                events.AddiOS(ios => ios.OnActivated(async app =>
                {
                    // RUN STARTUP CODE HERE
                }));
#endif
            })

            ...
```

Interestingly, "FinishedLaunching" did not work even though the [description ](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle?view=net-maui-8.0#ios-and-mac-catalyst)is similar.

**Comment by asi-evin** [comment]
Ok, I think I see something. It appears on startup, there are no scenes with the activation state "Foreground Active". However, a Key Window DOES exist. Any chance you could try adding the following to "GetActiveScene" or "GetActiveWindow":

```c#
if (connectedScene == null)
{
    connectedScene = UIApplication.SharedApplication.ConnectedScenes
        .OfType<UIWindowScene>()
        .LastOrDefault(x => x.KeyWindow != null);
}
```

If you prefer, I could try and do it, but I wouldn't be able to get to it for a while, and you are more likely to be more familiar with the best place to add this, how it may affect other things, or whether it's a dumb idea in the first place... And you have the code base at your fingertips.

I WAS able to use this with a test project, and I did get a KeyWindow back when I overrode "OnStart" in "App.xaml.cs", but I don't know if this is enough to ensure we would still get a Dialog to show.

**Comment by Alex-Dobrynin** [comment]
@asi-evin I cannot do it, because user can have many windows and therefore many scenes, we must show dialogs only on foreground and active scene (read foreground active window if it was in Windows OS)
